export const theme = {
  green: "#b1dd8c",
  greenDark: "#669c35",
  greenDarker: "#4e7828",
  greenLight: "#f0f9e4",
  greenMid: "#dff0c4",
  orange: "#e07b3a",
  cream: "#f9faf5",
  white: "#ffffff",
  charcoal: "#1e2a12",
  bodyText: "#374a1f",
  gray: "#7a8c6a",
  grayLight: "#edf0e8",
  grayBorder: "#dce3d4",
  red: "#d95f4b",
  yellow: "#e8c840",
};

export const storeColors = {
  "No Frills": "#e8a800",
  "Walmart": "#0071CE",
  "Loblaws": "#C8102E",
  "Metro": "#005B99",
  "Food Basics": "#e31837",
  "Farah Foods": "#005DAA",
};

export const storeLogos = {
  "No Frills": "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/nofrills.png",
  "Walmart":   "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/walmart.png",
  "Loblaws":   "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/loblaws.png",
  "Metro":     "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/metro.png",
  "Farah Foods":    "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/costco.png",
  "Food Basics": "https://res.cloudinary.com/dojayxyvx/image/upload/v1/stores/freshco.png",
};

export const stores = ["No Frills", "Walmart", "Loblaws", "Metro", "Costco", "Food Basics"];

export const allCategories = [
  { label: "Fruits",     emoji: "🍎" },
  { label: "Veggies",    emoji: "🥦" },
  { label: "Dairy",      emoji: "🥛" },
  { label: "Eggs",       emoji: "🥚" },
  { label: "Meat",       emoji: "🥩" },
  { label: "Seafood",    emoji: "🐟" },
  { label: "Cheese",     emoji: "🧀" },
  { label: "Bakery",     emoji: "🍞" },
  { label: "Frozen",     emoji: "🧊" },
  { label: "Snacks",     emoji: "🍿" },
  { label: "Drinks",     emoji: "🧃" },
  { label: "Breakfast",  emoji: "🥞" },
  { label: "Deli",       emoji: "🥓" },
  { label: "Pasta",      emoji: "🍝" },
  { label: "Canned",     emoji: "🥫" },
  { label: "Condiments", emoji: "🧴" },
  { label: "Organic",    emoji: "🌿" },
  { label: "Personal",   emoji: "🧼" },
];

export const categoryItems = {
  Fruits: [
    { id: "f1",  name: "Bananas (bunch)",       emoji: "🍌" },
    { id: "f2",  name: "Apples – Gala",          emoji: "🍎" },
    { id: "f3",  name: "Apples – Fuji",          emoji: "🍎" },
    { id: "f4",  name: "Apples – Granny Smith",  emoji: "🍏" },
    { id: "f5",  name: "Oranges (bag)",           emoji: "🍊" },
    { id: "f6",  name: "Strawberries (1lb)",      emoji: "🍓" },
    { id: "f7",  name: "Blueberries (pint)",      emoji: "🫐" },
    { id: "f8",  name: "Raspberries",             emoji: "🫐" },
    { id: "f9",  name: "Grapes – Red",            emoji: "🍇" },
    { id: "f10", name: "Grapes – Green",          emoji: "🍇" },
    { id: "f11", name: "Watermelon (whole)",      emoji: "🍉" },
    { id: "f12", name: "Watermelon (cut)",        emoji: "🍉" },
    { id: "f13", name: "Mango",                   emoji: "🥭" },
    { id: "f14", name: "Pineapple",               emoji: "🍍" },
    { id: "f15", name: "Peaches",                 emoji: "🍑" },
    { id: "f16", name: "Lemons",                  emoji: "🍋" },
    { id: "f17", name: "Limes",                   emoji: "🍋" },
    { id: "f18", name: "Avocados",                emoji: "🥑" },
    { id: "f19", name: "Cherries",                emoji: "🍒" },
    { id: "f20", name: "Kiwi",                    emoji: "🥝" },
  ],
  Veggies: [
    { id: "v1",  name: "Broccoli (head)",         emoji: "🥦" },
    { id: "v2",  name: "Cauliflower",             emoji: "🥦" },
    { id: "v3",  name: "Spinach (bag)",           emoji: "🥬" },
    { id: "v4",  name: "Mixed Greens",            emoji: "🥬" },
    { id: "v5",  name: "Romaine Lettuce",         emoji: "🥬" },
    { id: "v6",  name: "Kale (bunch)",            emoji: "🥬" },
    { id: "v7",  name: "Baby Carrots (bag)",      emoji: "🥕" },
    { id: "v8",  name: "Whole Carrots",           emoji: "🥕" },
    { id: "v9",  name: "Celery (bunch)",          emoji: "🥬" },
    { id: "v10", name: "Cucumber",               emoji: "🥒" },
    { id: "v11", name: "Zucchini",               emoji: "🥒" },
    { id: "v12", name: "Bell Peppers – Red",     emoji: "🫑" },
    { id: "v13", name: "Bell Peppers – Mixed",   emoji: "🫑" },
    { id: "v14", name: "Cherry Tomatoes",        emoji: "🍅" },
    { id: "v15", name: "Roma Tomatoes",          emoji: "🍅" },
    { id: "v16", name: "White Onions",           emoji: "🧅" },
    { id: "v17", name: "Red Onions",             emoji: "🧅" },
    { id: "v18", name: "Garlic (bulb)",          emoji: "🧄" },
    { id: "v19", name: "Russet Potatoes (bag)",  emoji: "🥔" },
    { id: "v20", name: "Sweet Potatoes",         emoji: "🍠" },
    { id: "v21", name: "Corn (cob)",             emoji: "🌽" },
    { id: "v22", name: "Mushrooms (227g)",       emoji: "🍄" },
    { id: "v23", name: "Green Beans",            emoji: "🫘" },
    { id: "v24", name: "Asparagus",              emoji: "🌿" },
  ],
  Dairy: [
    { id: "d1",  name: "Whole Milk (4L)",        emoji: "🥛" },
    { id: "d2",  name: "2% Milk (4L)",           emoji: "🥛" },
    { id: "d3",  name: "Skim Milk (4L)",         emoji: "🥛" },
    { id: "d4",  name: "Oat Milk",               emoji: "🥛" },
    { id: "d5",  name: "Almond Milk",            emoji: "🥛" },
    { id: "d6",  name: "Soy Milk",               emoji: "🥛" },
    { id: "d7",  name: "Lactose-Free Milk",      emoji: "🥛" },
    { id: "d8",  name: "Coconut Milk",           emoji: "🥛" },
    { id: "d9",  name: "Butter (454g)",          emoji: "🧈" },
    { id: "d10", name: "Salted Butter",          emoji: "🧈" },
    { id: "d11", name: "Greek Yogurt (Plain)",   emoji: "🫙" },
    { id: "d12", name: "Vanilla Yogurt",         emoji: "🫙" },
    { id: "d13", name: "Strawberry Yogurt",      emoji: "🫙" },
    { id: "d14", name: "Sour Cream",             emoji: "🫙" },
    { id: "d15", name: "Heavy Cream",            emoji: "🫙" },
    { id: "d16", name: "Whipping Cream",         emoji: "🫙" },
  ],
  Eggs: [
    { id: "e1",  name: "Large Eggs (12pk)",      emoji: "🥚" },
    { id: "e2",  name: "Large Eggs (18pk)",      emoji: "🥚" },
    { id: "e3",  name: "Extra Large Eggs (12pk)",emoji: "🥚" },
    { id: "e4",  name: "Free-Run Eggs (12pk)",   emoji: "🥚" },
    { id: "e5",  name: "Free-Range Eggs (12pk)", emoji: "🥚" },
    { id: "e6",  name: "Organic Eggs (12pk)",    emoji: "🥚" },
    { id: "e7",  name: "Omega-3 Eggs (12pk)",    emoji: "🥚" },
    { id: "e8",  name: "Brown Eggs (12pk)",      emoji: "🥚" },
    { id: "e9",  name: "Egg Whites (carton)",    emoji: "🥚" },
  ],
  Meat: [
    { id: "m1",  name: "Chicken Breasts",        emoji: "🍗" },
    { id: "m2",  name: "Chicken Thighs",         emoji: "🍗" },
    { id: "m3",  name: "Whole Chicken",          emoji: "🍗" },
    { id: "m4",  name: "Ground Beef (lean)",     emoji: "🥩" },
    { id: "m5",  name: "Ground Beef (extra lean)",emoji: "🥩" },
    { id: "m6",  name: "Beef Steak – Ribeye",   emoji: "🥩" },
    { id: "m7",  name: "Beef Steak – Sirloin",  emoji: "🥩" },
    { id: "m8",  name: "Beef Stew Chunks",       emoji: "🥩" },
    { id: "m9",  name: "Ground Turkey",          emoji: "🍗" },
    { id: "m10", name: "Turkey Breast",          emoji: "🍗" },
    { id: "m11", name: "Pork Chops",             emoji: "🥩" },
    { id: "m12", name: "Pork Tenderloin",        emoji: "🥩" },
    { id: "m13", name: "Bacon (375g)",           emoji: "🥓" },
    { id: "m14", name: "Sausages",               emoji: "🌭" },
    { id: "m15", name: "Lamb Chops",             emoji: "🥩" },
  ],
  Seafood: [
    { id: "sf1", name: "Salmon Fillet",          emoji: "🐟" },
    { id: "sf2", name: "Tilapia Fillet",         emoji: "🐟" },
    { id: "sf3", name: "Cod Fillet",             emoji: "🐟" },
    { id: "sf4", name: "Shrimp – Frozen (bag)",  emoji: "🦐" },
    { id: "sf5", name: "Shrimp – Fresh",         emoji: "🦐" },
    { id: "sf6", name: "Scallops",               emoji: "🐚" },
    { id: "sf7", name: "Mussels",                emoji: "🐚" },
    { id: "sf8", name: "Canned Tuna",            emoji: "🥫" },
    { id: "sf9", name: "Canned Salmon",          emoji: "🥫" },
    { id: "sf10",name: "Fish Sticks (frozen)",   emoji: "🐟" },
  ],
  Cheese: [
    { id: "c1",  name: "Cheddar – Mild",         emoji: "🧀" },
    { id: "c2",  name: "Cheddar – Old/Sharp",    emoji: "🧀" },
    { id: "c3",  name: "Mozzarella",             emoji: "🧀" },
    { id: "c4",  name: "Parmesan (block)",        emoji: "🧀" },
    { id: "c5",  name: "Parmesan (grated)",       emoji: "🧀" },
    { id: "c6",  name: "Brie",                   emoji: "🧀" },
    { id: "c7",  name: "Gouda",                  emoji: "🧀" },
    { id: "c8",  name: "Swiss",                  emoji: "🧀" },
    { id: "c9",  name: "Feta",                   emoji: "🧀" },
    { id: "c10", name: "Ricotta",                emoji: "🧀" },
    { id: "c11", name: "Marble Cheese",          emoji: "🧀" },
    { id: "c12", name: "Cheese Slices (18pk)",   emoji: "🧀" },
    { id: "c13", name: "Goat Cheese",            emoji: "🧀" },
    { id: "c14", name: "Pepper Jack",            emoji: "🧀" },
    { id: "c15", name: "Shredded Mozzarella",    emoji: "🧀" },
    { id: "c16", name: "Shredded Cheddar",       emoji: "🧀" },
    { id: "c17", name: "Cream Cheese",           emoji: "🧀" },
    { id: "c18", name: "Havarti",                emoji: "🧀" },
  ],
  Bakery: [
    { id: "b1",  name: "White Sandwich Bread",   emoji: "🍞" },
    { id: "b2",  name: "Whole Wheat Bread",      emoji: "🍞" },
    { id: "b3",  name: "Multigrain Bread",       emoji: "🍞" },
    { id: "b4",  name: "Sourdough Loaf",         emoji: "🍞" },
    { id: "b5",  name: "Rye Bread",              emoji: "🍞" },
    { id: "b6",  name: "Gluten-Free Bread",      emoji: "🍞" },
    { id: "b7",  name: "Baguette",               emoji: "🥖" },
    { id: "b8",  name: "Ciabatta Roll",          emoji: "🥖" },
    { id: "b9",  name: "Hamburger Buns (8pk)",   emoji: "🍔" },
    { id: "b10", name: "Hot Dog Buns (8pk)",     emoji: "🌭" },
    { id: "b11", name: "English Muffins (6pk)",  emoji: "🫓" },
    { id: "b12", name: "Pita Bread (6pk)",       emoji: "🫓" },
    { id: "b13", name: "Naan (4pk)",             emoji: "🫓" },
    { id: "b14", name: "Tortillas – Flour (10pk)",emoji: "🫓" },
    { id: "b15", name: "Tortillas – Corn (10pk)",emoji: "🫓" },
    { id: "b16", name: "Bagels (6pk)",           emoji: "🥯" },
    { id: "b17", name: "Croissants (4pk)",       emoji: "🥐" },
  ],
  Frozen: [
    { id: "fr1", name: "Pizza – Pepperoni",      emoji: "🍕" },
    { id: "fr2", name: "Pizza – Cheese",         emoji: "🍕" },
    { id: "fr3", name: "Frozen Fries",           emoji: "🍟" },
    { id: "fr4", name: "Frozen Mixed Veggies",   emoji: "🫘" },
    { id: "fr5", name: "Frozen Edamame",         emoji: "🫘" },
    { id: "fr6", name: "Frozen Berries (mixed)", emoji: "🫐" },
    { id: "fr7", name: "Frozen Mango Chunks",    emoji: "🥭" },
    { id: "fr8", name: "Ice Cream – Vanilla",    emoji: "🍦" },
    { id: "fr9", name: "Ice Cream – Chocolate",  emoji: "🍦" },
    { id: "fr10",name: "Frozen Waffles (8pk)",   emoji: "🧇" },
    { id: "fr11",name: "Frozen Burritos",        emoji: "🌯" },
    { id: "fr12",name: "Frozen Dumplings",       emoji: "🥟" },
    { id: "fr13",name: "Frozen Peas",            emoji: "🫘" },
    { id: "fr14",name: "Frozen Corn",            emoji: "🌽" },
  ],
  Snacks: [
    { id: "sn1", name: "Lay's Classic Chips",    emoji: "🍟" },
    { id: "sn2", name: "Doritos – Nacho",        emoji: "🍟" },
    { id: "sn3", name: "Popcorn (microwave 3pk)",emoji: "🍿" },
    { id: "sn4", name: "Pretzels",               emoji: "🥨" },
    { id: "sn5", name: "Rice Cakes",             emoji: "⬜" },
    { id: "sn6", name: "Granola Bars (6pk)",     emoji: "🍫" },
    { id: "sn7", name: "Trail Mix",              emoji: "🥜" },
    { id: "sn8", name: "Mixed Nuts",             emoji: "🥜" },
    { id: "sn9", name: "Peanut Butter",          emoji: "🥜" },
    { id: "sn10",name: "Almond Butter",          emoji: "🥜" },
    { id: "sn11",name: "Crackers (box)",         emoji: "🍘" },
    { id: "sn12",name: "Hummus",                 emoji: "🫙" },
    { id: "sn13",name: "Chocolate Bar",          emoji: "🍫" },
    { id: "sn14",name: "Protein Bar",            emoji: "🍫" },
  ],
  Drinks: [
    { id: "bv1", name: "Orange Juice (2L)",      emoji: "🧃" },
    { id: "bv2", name: "Apple Juice (2L)",       emoji: "🧃" },
    { id: "bv3", name: "Sparkling Water (12pk)", emoji: "💧" },
    { id: "bv4", name: "Still Water (24pk)",     emoji: "💧" },
    { id: "bv5", name: "Coffee – Ground",        emoji: "☕" },
    { id: "bv6", name: "Coffee – Whole Bean",    emoji: "☕" },
    { id: "bv7", name: "Coffee Pods (12pk)",     emoji: "☕" },
    { id: "bv8", name: "Tea (box)",              emoji: "🍵" },
    { id: "bv9", name: "Green Tea",              emoji: "🍵" },
    { id: "bv10",name: "Lemonade (2L)",          emoji: "🍋" },
    { id: "bv11",name: "Gatorade",               emoji: "🥤" },
    { id: "bv12",name: "Coca-Cola (12pk)",       emoji: "🥤" },
    { id: "bv13",name: "Diet Coke (12pk)",       emoji: "🥤" },
    { id: "bv14",name: "Oat Milk Latte",         emoji: "☕" },
  ],
  Breakfast: [
    { id: "bk1", name: "Cheerios",               emoji: "🥣" },
    { id: "bk2", name: "Corn Flakes",            emoji: "🥣" },
    { id: "bk3", name: "Granola",                emoji: "🥣" },
    { id: "bk4", name: "Instant Oatmeal (10pk)", emoji: "🥣" },
    { id: "bk5", name: "Rolled Oats (1kg)",      emoji: "🌾" },
    { id: "bk6", name: "Pancake Mix",            emoji: "🥞" },
    { id: "bk7", name: "Maple Syrup (250ml)",    emoji: "🍁" },
    { id: "bk8", name: "Jam – Strawberry",       emoji: "🫙" },
    { id: "bk9", name: "Jam – Raspberry",        emoji: "🫙" },
    { id: "bk10",name: "Nutella (400g)",         emoji: "🫙" },
    { id: "bk11",name: "Protein Powder – Vanilla",emoji: "🥤" },
    { id: "bk12",name: "Protein Powder – Chocolate",emoji: "🥤" },
    { id: "bk13",name: "Chia Seeds",             emoji: "🌱" },
    { id: "bk14",name: "Flax Seeds",             emoji: "🌱" },
  ],
  Deli: [
    { id: "dl1", name: "Deli Ham (sliced)",       emoji: "🥩" },
    { id: "dl2", name: "Turkey Deli Meat",        emoji: "🍗" },
    { id: "dl3", name: "Salami",                  emoji: "🥩" },
    { id: "dl4", name: "Pepperoni",               emoji: "🥩" },
    { id: "dl5", name: "Prosciutto",              emoji: "🥩" },
    { id: "dl6", name: "Roast Beef (sliced)",     emoji: "🥩" },
    { id: "dl7", name: "Smoked Salmon",           emoji: "🐟" },
    { id: "dl8", name: "Chicken Strips (cooked)", emoji: "🍗" },
    { id: "dl9", name: "Coleslaw",                emoji: "🥗" },
    { id: "dl10",name: "Potato Salad",            emoji: "🥗" },
  ],
  Pasta: [
    { id: "pa1", name: "Spaghetti",               emoji: "🍝" },
    { id: "pa2", name: "Penne",                   emoji: "🍝" },
    { id: "pa3", name: "Fusilli",                 emoji: "🍝" },
    { id: "pa4", name: "Linguine",                emoji: "🍝" },
    { id: "pa5", name: "Lasagna Sheets",          emoji: "🍝" },
    { id: "pa6", name: "Pasta Sauce – Marinara",  emoji: "🫙" },
    { id: "pa7", name: "Pasta Sauce – Arrabbiata",emoji: "🫙" },
    { id: "pa8", name: "Pasta Sauce – Alfredo",   emoji: "🫙" },
    { id: "pa9", name: "White Rice (2kg)",        emoji: "🍚" },
    { id: "pa10",name: "Brown Rice (2kg)",        emoji: "🍚" },
    { id: "pa11",name: "Basmati Rice (2kg)",      emoji: "🍚" },
    { id: "pa12",name: "Jasmine Rice (2kg)",      emoji: "🍚" },
    { id: "pa13",name: "Quinoa (500g)",           emoji: "🌾" },
    { id: "pa14",name: "Couscous",                emoji: "🌾" },
  ],
  Canned: [
    { id: "ca1", name: "Canned Tomatoes",         emoji: "🥫" },
    { id: "ca2", name: "Tomato Paste",            emoji: "🥫" },
    { id: "ca3", name: "Canned Chickpeas",        emoji: "🥫" },
    { id: "ca4", name: "Canned Black Beans",      emoji: "🥫" },
    { id: "ca5", name: "Canned Lentils",          emoji: "🥫" },
    { id: "ca6", name: "Canned Corn",             emoji: "🥫" },
    { id: "ca7", name: "Canned Tuna",             emoji: "🥫" },
    { id: "ca8", name: "Canned Salmon",           emoji: "🥫" },
    { id: "ca9", name: "Canned Coconut Milk",     emoji: "🥫" },
    { id: "ca10",name: "Chicken Broth (900ml)",   emoji: "🥫" },
    { id: "ca11",name: "Vegetable Broth (900ml)", emoji: "🥫" },
    { id: "ca12",name: "Canned Soup",             emoji: "🥫" },
  ],
  Condiments: [
    { id: "co1", name: "Ketchup",                 emoji: "🧴" },
    { id: "co2", name: "Mustard",                 emoji: "🧴" },
    { id: "co3", name: "Mayonnaise",              emoji: "🧴" },
    { id: "co4", name: "Olive Oil (500ml)",       emoji: "🫙" },
    { id: "co5", name: "Canola Oil (1L)",         emoji: "🫙" },
    { id: "co6", name: "Soy Sauce",               emoji: "🫙" },
    { id: "co7", name: "Hot Sauce",               emoji: "🌶️" },
    { id: "co8", name: "BBQ Sauce",               emoji: "🫙" },
    { id: "co9", name: "Ranch Dressing",          emoji: "🫙" },
    { id: "co10",name: "Balsamic Vinegar",        emoji: "🫙" },
    { id: "co11",name: "Salt",                    emoji: "🧂" },
    { id: "co12",name: "Black Pepper",            emoji: "🧂" },
    { id: "co13",name: "All-Purpose Flour (2kg)", emoji: "🌾" },
    { id: "co14",name: "Sugar (2kg)",             emoji: "🧂" },
  ],
  Organic: [
    { id: "or1", name: "Organic Bananas",         emoji: "🍌" },
    { id: "or2", name: "Organic Apples (bag)",    emoji: "🍎" },
    { id: "or3", name: "Organic Spinach (bag)",   emoji: "🥬" },
    { id: "or4", name: "Organic Mixed Greens",    emoji: "🥬" },
    { id: "or5", name: "Organic Carrots (bag)",   emoji: "🥕" },
    { id: "or6", name: "Organic Whole Milk",      emoji: "🥛" },
    { id: "or7", name: "Organic Eggs (12pk)",     emoji: "🥚" },
    { id: "or8", name: "Organic Greek Yogurt",    emoji: "🫙" },
    { id: "or9", name: "Organic Chicken Breasts", emoji: "🍗" },
    { id: "or10",name: "Organic Ground Beef",     emoji: "🥩" },
    { id: "or11",name: "Organic Oats (1kg)",      emoji: "🌾" },
    { id: "or12",name: "Organic Olive Oil",       emoji: "🫙" },
  ],
  Personal: [
    { id: "h1",  name: "Paper Towels (6pk)",      emoji: "🧻" },
    { id: "h2",  name: "Toilet Paper (12pk)",     emoji: "🧻" },
    { id: "h3",  name: "Dish Soap",               emoji: "🧴" },
    { id: "h4",  name: "Laundry Detergent",       emoji: "🧴" },
    { id: "h5",  name: "All-Purpose Cleaner",     emoji: "🧹" },
    { id: "h6",  name: "Garbage Bags (20pk)",     emoji: "🗑️" },
    { id: "h7",  name: "Ziplock Bags (freezer)",  emoji: "🗑️" },
    { id: "h8",  name: "Aluminum Foil",           emoji: "✨" },
    { id: "h9",  name: "Sponges (3pk)",           emoji: "🧽" },
    { id: "h10", name: "Shampoo",                 emoji: "🧴" },
    { id: "h11", name: "Conditioner",             emoji: "🧴" },
    { id: "h12", name: "Body Wash",               emoji: "🧼" },
    { id: "h13", name: "Toothpaste",              emoji: "🪥" },
    { id: "h14", name: "Deodorant",               emoji: "🧴" },
  ],
};

export const mockDeals = [
  { id: 1, name: "Bananas",        store: "No Frills", price: "$0.49/lb", emoji: "🍌", savings: "32% off" },
  { id: 2, name: "Chicken Breast", store: "Walmart",   price: "$6.99/kg", emoji: "🍗", savings: "18% off" },
  { id: 3, name: "2% Milk 4L",    store: "Loblaws",   price: "$4.99",    emoji: "🥛", savings: "10% off" },
  { id: 4, name: "Strawberries",   store: "Metro",     price: "$2.99",    emoji: "🍓", savings: "25% off" },
  { id: 5, name: "Sourdough",      store: "FreshCo",   price: "$3.49",    emoji: "🍞", savings: "15% off" },
  { id: 6, name: "Greek Yogurt",   store: "No Frills", price: "$2.79",    emoji: "🥛", savings: "20% off" },
];

export const inputStyle = {
  width: "100%", padding: "12px 16px",
  background: "#f9faf5", border: "1.5px solid #dce3d4",
  borderRadius: 10, fontSize: 14,
  fontFamily: "'Nunito', sans-serif",
  outline: "none", boxSizing: "border-box",
  color: "#1e2a12", transition: "border-color 0.2s",
};

export const qtyBtnStyle = {
  width: 30, height: 30, borderRadius: 8, border: "none",
  background: "#edf0e8", color: "#374a1f", fontWeight: 700,
  fontSize: 16, cursor: "pointer", display: "flex",
  alignItems: "center", justifyContent: "center",
};